[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

[program:jupyterlab]
command=jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
directory=/storage
autostart=true
autorestart=true
stdout_logfile=/var/log/jupyter.log
stderr_logfile=/var/log/jupyter.log

[program:comfyui]
command=python /app/ComfyUI/main.py --listen 0.0.0.0 --port 8188 --preview-method auto
directory=/app/ComfyUI
autostart=true
autorestart=true
stdout_logfile=/var/log/comfyui.log
stderr_logfile=/var/log/comfyui.log
environment=PYTHONUNBUFFERED="1"
